feat : dev branch merge 중 충돌 해결

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -10,6 +10,17 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+    env:
+      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
+      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
+      JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
+      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
+      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
+      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
+      TOSS_CLIENT_KEY: ${{ secrets.TOSS_CLIENT_KEY }}
+      TOSS_SECRET_KEY: ${{ secrets.TOSS_SECRET_KEY }}
+      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
+
     services:
       mysql:
         image: mysql:8.0
@@ -44,12 +55,31 @@ jobs:
             sleep 1
           done
 
+      - name: Check for environment variables
+        run: |
+          VARS=("GOOGLE_CLIENT_ID" "GOOGLE_CLIENT_SECRET" "JWT_ISSUER" "JWT_SECRET_KEY" "AWS_ACCESS_KEY" "AWS_SECRET_KEY" "TOSS_CLIENT_KEY" "TOSS_SECRET_KEY" "SENTRY_DSN")
+          ERROR_FOUND=0
+
+          for var in "${VARS[@]}"; do
+            if [[ -z "${!var}" ]]; then
+              echo "‼️‼️ ERROR: Cannot found [ $var ] ‼️‼️"
+              ERROR_FOUND=1
+            else
+              echo "✅✅ Checked success [ $var ] ✅✅"
+            fi
+          done
+
+          if [[ $ERROR_FOUND -eq 1 ]]; then
+            exit 1
+          fi
+
       - name: Build with Gradle (Using CI Profile)
-        run: ./gradlew clean build -Dspring.profiles.active=ci
+        run: ./gradlew clean build
         env:
           SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/flight_booking
           SPRING_DATASOURCE_USERNAME: root
           SPRING_DATASOURCE_PASSWORD: rootpassword
+          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
 
       - name: Get current time
         uses: josStorer/get-current-time@v2.0.2
